<?php
/**
 * Contract for a backend raster renderer used by the Divi screenshot ability.
 *
 * @package Divi5WooCommerceMCP
 */

declare(strict_types=1);

namespace CodeLearner\Divi5WooCommerceMCP\Divi;

interface ScreenshotEngineInterface {
	/**
	 * Return a stable machine-readable renderer identifier.
	 */
	public function id(): string;

	/**
	 * Whether the renderer can produce real frontend pixels in this environment.
	 */
	public function is_available(): bool;

	/**
	 * Render the supplied same-site WordPress URL to real image bytes.
	 *
	 * Implementations must use an actual HTML/CSS layout engine. Reconstructed or
	 * approximate previews generated from DOMDocument, GD, Imagick, PDF layout,
	 * or server-side block markup alone do not satisfy this contract.
	 *
	 * Required success result:
	 * - success: true
	 * - image_data: raw PNG/JPEG bytes
	 *
	 * Optional result keys:
	 * - warnings: array<int, mixed>
	 * - render_method: string
	 * - error_code: string|null
	 * - error_message: string|null
	 *
	 * @param array<string, mixed> $request Render request generated by the plugin.
	 * @return array<string, mixed>
	 */
	public function render( array $request ): array;
}
